In [1]:
import numpy as np

In [2]:
n = 5

In [3]:
mat = np.random.randint(4, size=(10000,n))
mat

array([[2, 0, 1, 3, 3],
       [1, 2, 3, 0, 0],
       [2, 0, 0, 3, 2],
       ...,
       [2, 2, 3, 3, 1],
       [1, 1, 3, 1, 2],
       [0, 0, 3, 1, 0]])

In [4]:
seq = mat[0]

In [5]:
seq

array([2, 0, 1, 3, 3])

In [6]:
mat2 = mat[1:]
mat2

array([[1, 2, 3, 0, 0],
       [2, 0, 0, 3, 2],
       [3, 3, 1, 1, 3],
       ...,
       [2, 2, 3, 3, 1],
       [1, 1, 3, 1, 2],
       [0, 0, 3, 1, 0]])

In [7]:
seq

array([2, 0, 1, 3, 3])

In [8]:
mat2

array([[1, 2, 3, 0, 0],
       [2, 0, 0, 3, 2],
       [3, 3, 1, 1, 3],
       ...,
       [2, 2, 3, 3, 1],
       [1, 1, 3, 1, 2],
       [0, 0, 3, 1, 0]])

In [9]:
seq.shape, mat2.shape

((5,), (9999, 5))

In [10]:
n-1
seqpad = np.hstack([[5]*(n-1), seq, [5]*(n-1)])
seqpad

array([5, 5, 5, 5, 2, 0, 1, 3, 3, 5, 5, 5, 5])

In [11]:
for i in range(2*n-1):
    overlap = np.sum(seqpad[i:i+5]==mat2, axis=1)
    print(overlap)
    print(overlap.shape)
    # print(seqpad[i:i+5]-mat2)

[0 1 0 ... 0 1 0]
(9999,)
[1 0 0 ... 0 0 1]
(9999,)
[1 0 0 ... 1 0 0]
(9999,)
[1 1 2 ... 1 1 1]
(9999,)
[0 3 2 ... 2 0 1]
(9999,)
[1 1 0 ... 2 2 2]
(9999,)
[2 0 1 ... 1 2 1]
(9999,)
[0 0 2 ... 0 0 0]
(9999,)
[0 0 1 ... 0 0 0]
(9999,)
